adb -s `./pixel4.sh` shell date +%T.%N >pixel4.txt
adb -s `./pixel5.sh` shell date +%T.%N >pixel5.txt
adb -s `./pixel4.sh` shell date +%T.%N >>pixel4.txt
adb -s `./pixel5.sh` shell date +%T.%N >>pixel5.txt
adb -s `./pixel4.sh` shell date +%T.%N >>pixel4.txt
adb -s `./pixel5.sh` shell date +%T.%N >>pixel5.txt
adb -s `./pixel4.sh` shell date +%T.%N >>pixel4.txt
adb -s `./pixel5.sh` shell date +%T.%N >>pixel5.txt
adb -s `./pixel4.sh` shell date +%T.%N >>pixel4.txt
adb -s `./pixel5.sh` shell date +%T.%N >>pixel5.txt
adb -s `./pixel4.sh` shell date +%T.%N >>pixel4.txt
adb -s `./pixel5.sh` shell date +%T.%N >>pixel5.txt
adb -s `./pixel4.sh` shell date +%T.%N >>pixel4.txt
adb -s `./pixel5.sh` shell date +%T.%N >>pixel5.txt
adb -s `./pixel4.sh` shell date +%T.%N >>pixel4.txt
adb -s `./pixel5.sh` shell date +%T.%N >>pixel5.txt
adb -s `./pixel4.sh` shell date +%T.%N >>pixel4.txt
adb -s `./pixel5.sh` shell date +%T.%N >>pixel5.txt
adb -s `./pixel4.sh` shell date +%T.%N >>pixel4.txt
adb -s `./pixel5.sh` shell date +%T.%N >>pixel5.txt
adb -s `./pixel4.sh` shell date +%T.%N >>pixel4.txt
adb -s `./pixel5.sh` shell date +%T.%N >>pixel5.txt
adb -s `./pixel4.sh` shell date +%T.%N >>pixel4.txt
adb -s `./pixel5.sh` shell date +%T.%N >>pixel5.txt
adb -s `./pixel4.sh` shell date +%T.%N >>pixel4.txt
adb -s `./pixel5.sh` shell date +%T.%N >>pixel5.txt
adb -s `./pixel4.sh` shell date +%T.%N >>pixel4.txt
adb -s `./pixel5.sh` shell date +%T.%N >>pixel5.txt
adb -s `./pixel4.sh` shell date +%T.%N >>pixel4.txt
adb -s `./pixel5.sh` shell date +%T.%N >>pixel5.txt
adb -s `./pixel4.sh` shell date +%T.%N >>pixel4.txt
adb -s `./pixel5.sh` shell date +%T.%N >>pixel5.txt
adb -s `./pixel4.sh` shell date +%T.%N >>pixel4.txt
adb -s `./pixel5.sh` shell date +%T.%N >>pixel5.txt
adb -s `./pixel4.sh` shell date +%T.%N >>pixel4.txt
adb -s `./pixel5.sh` shell date +%T.%N >>pixel5.txt
adb -s `./pixel4.sh` shell date +%T.%N >>pixel4.txt
adb -s `./pixel5.sh` shell date +%T.%N >>pixel5.txt
adb -s `./pixel4.sh` shell date +%T.%N >>pixel4.txt
adb -s `./pixel5.sh` shell date +%T.%N >>pixel5.txt
adb -s `./pixel4.sh` shell date +%T.%N >>pixel4.txt
adb -s `./pixel5.sh` shell date +%T.%N >>pixel5.txt
adb -s `./pixel4.sh` shell date +%T.%N >>pixel4.txt
adb -s `./pixel5.sh` shell date +%T.%N >>pixel5.txt
adb -s `./pixel4.sh` shell date +%T.%N >>pixel4.txt
adb -s `./pixel5.sh` shell date +%T.%N >>pixel5.txt
adb -s `./pixel4.sh` shell date +%T.%N >>pixel4.txt
adb -s `./pixel5.sh` shell date +%T.%N >>pixel5.txt
adb -s `./pixel4.sh` shell date +%T.%N >>pixel4.txt
adb -s `./pixel5.sh` shell date +%T.%N >>pixel5.txt

